### PR TITLE
added issue template

### PR DESCRIPTION
**Pull request by jemmycodes**
# Pull Request Template

## Description

[Create Issue Template #26 ](https://github.com/abeg-help/frontend/issues/26)

## Related Issue

- Fixes # (26)

## Contribution Guidelines

Before submitting this pull request, please review our [Contribution Guidelines](https://github.com/abeg-help/frontend/blob/dev/CONTRIBUTING.md) to understand how to contribute to this project.

## Checklist

- [x] I have reviewed the Contribution Guidelines linked above.
- [x] I have tested my changes thoroughly and ensured that all existing tests pass.
- [x] I have provided clear and concise commit messages.
- [x] I have updated the project's documentation as necessary.

### CODE REVIEW

**Comment by Klin-Coders** [comment]
@jemmycodes kindly fill the pull request template and link any issue it is supposed to close

**Comment by jemmycodes** [comment]
[](https://github.com/abeg-help/frontend/issues/26)

**Comment by jemmycodes** [comment]
[Create Issue Template #26 ](https://github.com/abeg-help/frontend/issues/26)

**Review by Klin-Coders — APPROVED** [review]
Thank you for your contribution. LGTM

**Pull request merged**
