### PR TITLE
style(prettier-config): configured prettier to only utilize double quote for strings

### PR DESCRIPTION
**Pull request by Ryan-Zayne**
## Description

- Configured prettier to only use double quote for strings, ensuring formatting consistency

## Contribution Guidelines

Before submitting this pull request, please review our [Contribution Guidelines](https://github.com/abeg-help/frontend/blob/dev/CONTRIBUTING.md) to understand how to contribute to this project.

## Checklist

- [x] I have reviewed the Contribution Guidelines linked above.
- [x] I have tested my changes thoroughly and ensured that all existing tests pass.
- [x] I have provided clear and concise commit messages.
- [x] I have updated the project's documentation as necessary.

### CODE REVIEW

**Review by babblebey — CHANGES_REQUESTED** [review]
Great stuff @Ryan-Zayne 

Take this as a blocking review!

Kindly run `npm run format` on your working dir now, this will serve as a test for ensuring that the double quote `"` indeed works on format and it will also bring all the files up-to-date with the double quotes used all through.

This obviously mean you will commit the changes made to the entire repo file.

**Comment by Ryan-Zayne** [comment]
> Kindly run `npm run format` on your working dir now, this will serve as a test for ensuring that the double quote `"` indeed works on format and it will also bring all the files up-to-date with the double quotes used all through.
>

Done. Any thing else?

**Review by babblebey — APPROVED** [review]

**Comment by babblebey** [comment]
LG 🤲🏾

**Comment by Ryan-Zayne** [comment]
@289Volts I await your review

**Pull request merged**
