### PR TITLE
feat: add `storybookjs` to project

### LINKED ISSUE #69: Enhancement: Add `StorybookJS` to the Project
## Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Enhancement
- [ ] Other (Please specify)

## Description

StorybookJS is a tool for developing and testing UI components in isolation. It provides a development environment where we can showcase and interact with our UI components outside of the main application. This can significantly speed up development and improve the overall quality of our components.

We currently do not have StorybookJS integrated into our project. Adding this offer several benefits, with a few stated below:

- **Isolated Development**: Developers can work on UI components in isolation without the need to run the entire application.
- **Interactive Documentation**: We can create interactive documentation for our UI components, making it easier for developers to understand and use them.
- **Rapid Iteration**: Storybook allows for rapid iteration and testing of UI components, leading to faster development.
- **Visual Testing**: We can visually test our components in different states and scenarios.
- **Collaboration**: Storybook provides a platform for collaboration between designers and developers on component design and functionality.

## Details

I Propose adding StorybookJS to the project, here's a checklist of this planned to be done.

- [ ] **Installation**: We will install Storybook as a development dependency.
- [ ] **Configuration**: Configure Storybook to work with our project's tech stack.
- [ ] **Component Integration**: We will start by integrating our existing UI components or boilerplate one into Storybook.
- [ ] **Documentation**: Create Storybook stories and documentation for each UI component.
- [ ] **Testing**: We will use Storybook for visual and functional testing of our UI components.

## Reproduction Steps (For Bug Reports)

NA

## Expected Behavior (For Bug Reports)

NA

## Actual Behavior (For Bug Reports)

NA

## Additional Information

[Include any additional information that may help in resolving the issue, such as screenshots, logs, or any related links.]

## Would you like to contribute to fixing this issue?

- [x] Yes
- [ ] No

## Related Pull Requests (if any)

NA

## Failure Logs

NA

**Note:** Please make sure to follow the project's code of conduct and contribution guidelines when creating an issue. Thank you for contributing to our open-source project!

### PR DESCRIPTION
**Pull request by babblebey**
## Description

This Pull Request add `StorybookJS` to the project, a tool for developing and testing UI components in isolation, with a development environment where contributors can showcase and interact with UI components outside of the main application.

### Changes Made

- Added the `storybookjs` package and related addons packages
- Configure stories preview environment in `.storybook` directory
- Set up example stories as pointer/reference to creating stories for project component in the `stories` directory
- Refactored project folder structure, removing usage of `src` folder, moving initial content to `./` directory

## Related Issue

- Fixes #69

## Contribution Guidelines

Before submitting this pull request, please review our [Contribution Guidelines](https://github.com/abeg-help/frontend/blob/dev/CONTRIBUTING.md) to understand how to contribute to this project.

## Checklist

- [x] I have reviewed the Contribution Guidelines linked above.
- [x] I have tested my changes thoroughly and ensured that all existing tests pass.
- [x] I have provided clear and concise commit messages.
- [x] I have updated the project's documentation as necessary.

## Screenshots (if applicable)

[screencast-localhost_6006-2023.10.14-14_42_51.webm](https://github.com/abeg-help/frontend/assets/25631971/3aed2d3a-f8cf-4fb5-ba88-7c2b47216ef5)

## Additional context (if needed)

NA

### CODE REVIEW

**Comment by Ryan-Zayne** [comment]
@babblebey was there later any unanimous decision to add storybookJs to the mix?

I thought we all agreed to leave it out in favour of lowering the entry barrier for juniors devs, no?

**Comment by babblebey** [comment]
Yo @Ryan-Zayne 😃 

The addition came up later during a conversation I had with @Klin-Coders (which he went on and mentioned on the group chat that we would be adding it stating that I was gonna be working on it); proved somewhat of an imperative addition to aid documentation and testing of the component we implement tailored exactly to our usage/implementation context.

Storybook being barrier for junior developers isn't the case now and isn't to be compared to the forms of TDD haha 😃, the stories are in fact meant to aid these young professionals as it points them to a clearly documented means of using/integrating all existing components we have/will be implementing.

In the absence of this, these young professional will have to result to reading the components code bases or shadcn/radix-ui docs in attempt to try figure out how them components works and how to integrate them as needed. Now this obviously isn't gonna be easy on them young professionals.

**Comment by Ryan-Zayne** [comment]
Makes sense in that case👍

**Review by Ryan-Zayne — APPROVED** [review]

**Review by Klin-Coders — APPROVED** [review]
Great work @babblebey

**Pull request merged**
